### ISSUE TITLE
One more deprecation!

### ISSUE THREAD

**Issue by benogle** [abe33/minimap-color-highlight#11]
According to [our data](https://gist.github.com/benogle/6d09e295c84b717ef9b4), there is one remaining deprecation on this repo:

* Use ::dispose to cancel subscriptions instead of ::off

**Comment by benogle** [comment]
Likely this: https://github.com/abe33/minimap-color-highlight/blob/c38e2ef9cac88600d30e136851d200d55aecbefe/lib/minimap-color-highlight.coffee#L61

**Comment by abe33** [comment]
Oh, sorry, that's fixed now :).

**Comment by benogle** [comment]
:boom:
