### ISSUE TITLE
Still requiring atom-color-highlight

### ISSUE THREAD

**Issue by itsnotvalid** [abe33/minimap-color-highlight#12]
As seen on `atom-color-highlight`, it is replaced by `pigments`. Please update the dependencies.

**Comment by abe33** [comment]
The API between the two packages being really different I plan to make a different plugin for pigments, I just still haven't found the time to work on it, but thanks for your concern, I'll post an update here when I had advanced on that front.

**Comment by abe33** [comment]
Just published a first version of the pigments binding: https://atom.io/packages/minimap-pigments

**Comment by itsnotvalid** [comment]
Thanks for your quick work!
