### ISSUE TITLE
Could we disable polling?

### ISSUE THREAD

**Issue by despairblue** [abe33/minimap-color-highlight#3]
Would it be possible to disable the polling in [minimap-color-highlight-view](https://github.com/abe33/minimap-color-highlight/blob/master/lib/minimap-color-highlight-view.coffee#L46)? It's putting quite some load on the atom process after a while (not sure why, but it slowly eats it way up to 100% CPU and profiling showed that this method amounts to 30% of this, the other 70% might be side effects, dunno).

I'm asking because I haven't seen the use of polling in your other minmap plugins.

**Comment by abe33** [comment]
Sure, this is a legacy of the v3 era, I plan to clean up all the plugins before releasing v4, so I'll add this in the clean-up todos.

**Comment by despairblue** [comment]
thx
